language: php
php:
    - 5.6
    - 7.2
    - 7.3
    - 7.4
os:
    - linux
services:
    - mysql
addons:
    apt:
        sources:
        - mysql-5.7-trusty
        packages:
        - dpkg
        - mysql-server
        - mysql-client
    sonarcloud:
        organization: "webfiori"
        token:
            secure: AzKSX9z4fCXHum0fyYcMsYcNkUQRSxAbNprx4a3W43mro2sCfkqnLCAnz23wLOEqRE19FaEh26Bq6d+C7Z/Wr8g4m4xOFJv3DU2EdBNZs+EAqYSzVtFl8G0bQomuqOFvGwO68z6NA1jcLYqWX/gMRVuz5fujyhttDrrVOTzTCT4k57yfT6NhPjn5MVEX6ybUE8tfQlSXgEVPncE1d/YP5+mXrRtBxBU3uZFaLe0daB7pSt302LK+gGm9KSm6+Q9GaVsRKKNSKrzPVkCfBhbYeDcRgBxsbi36NqfnqvPtxyujDl2BZ1i8PuV7kGmzGRSLZOSyyY+RKx57GCF6Cd9aPHkrsBmq9rPJmQwykGPYuMoWAEa/3eBo0Sl7WwzypgcndtqDQm7eOTLmfuHGiwvm6EkrDXWuUjxdxMYZDmpL0m/FJr4rITFRgficPA8BzSASE+3nRLK25m10fcINElBeiHAzXHKLewPwRUpZlzFfqd4r6qUMt2NVO4oOdNuKefTlZ7A2wlmRogVKJWoMFPviTR1H+rtUmfhAJS6UAUfaYZf7Yh+saZHXbgmOPxfYRLoLrJKnNXzB6nziQKgO+75xIIXAbzEy21x+rtLCmYHbLE+VyR9AYfJRfDdoqOnqhTX8CVZNHMChWyXrRrZjSUO/uZMn00YuZ0Ag5YqERCaxHCw=
    
install:
    - sudo apt-get -y -q -m --no-install-suggests --no-install-recommends --allow-unauthenticated
      $(travis_apt_get_options) install dpkg mysql-server mysql-client
before_install:
    - sudo apt-get -q update
    - sudo apt-get -y install postfix
    - mysql -e 'create database if not exists testing_db;'
    - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('123456')
      where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    - sudo mysql_upgrade -u root -p123456
    - sudo service mysql restart
before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction
script:
    - phpunit --verbose --configuration phpunit.xml
after_success:
    - mysql -e 'drop database testing_db;'
    - bash <(curl -s https://codecov.io/bash)
    - sonar-scanner
