name: Build PHP 8.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  setup-mysql:
    name: Setup MySQL 
    uses: WebFiori/workflows/.github/workflows/setup-mysql.yaml@main
    with:
      database-name: 'testing_db'
      root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    secrets: inherit
    
  setup-mssql:
    name: Setup SQL Server 
    uses: WebFiori/workflows/.github/workflows/setup-sql-server.yaml@main
    with:
      database-name: 'testing_db'
      sa-password: ${{ secrets.SA_SQL_SERVER_PASSWORD }}
    secrets: inherit
    
  test:
    name: Run Tests
    uses: WebFiori/workflows/.github/workflows/test-php.yaml@main
    with:
      php-version: '8.1'
    secrets: inherit

  code-coverage:
    name: Coverage
    needs: test
    uses: WebFiori/workflows/.github/workflows/coverage-codecov.yaml@main
    with:
      php-version: '8.1'
      coverage-file: 'php-8.1-coverage.xml'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
        
          
